"""schedule place pool

Revision ID: c24bd64ba972
Revises: a9edbe2209ab
Create Date: 2026-08-11 15:20:48.119776

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c24bd64ba972"
down_revision: Union[str, Sequence[str], None] = "a9edbe2209ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_place_pool",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("places", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("searched_liked_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("searched_disliked_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["schedule_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    # ck_schedule_session_status(f4f8459f626b)의 drop은 autogenerate 오탐이라 뺐다 —
    # SQLModel이 Literal을 컬럼에 못 붙여서(app/models/schedule.py 주석 참고) 모델엔
    # 이 CHECK 제약이 안 보이고, autogenerate가 이를 "모델에 없으니 지워야 할 것"으로
    # 오인한다. 실제로는 계속 유지해야 하는 제약이라 여기서 건드리지 않는다.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedule_place_pool")
    # ### end Alembic commands ###
